goPath: /Users/joker/go
cryptVersion: 1
configPath: /Users/joker/go/src/examples/blockchain/solo/solo_single_org/config/blockchain-config.yaml
channels:
  - channelId: demochannel
    needListOnBlockEvent: true
    channelConfigPath: /Users/joker/go/src/examples/blockchain/solo/solo_single_org/artifacts/demo.tx
    orders:
      - ordererId: orderer0.demo.com
        ordererAddress: orderer0.demo.com
        ordererPort: 6050
    organizations:
      - organizationId: Org1MSP
        users:
          - userName: 'User1'
            admin: false
          - userName: 'admin'
            admin: true
        peers:
          - anchorPeers:
              - address: peer0.org1.demo.com
                port: 8051
                chainCodes:
                  - chainCodeId: democc
                    chainCodePath: examples/blockchain/solo/solo_single_org/chaincodes
                    needUpdate: false

